# Generated by Django 6.0.5 on 2026-06-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchises", "0005_matchplaying11"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1_overs",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_wickets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_overs",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_wickets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="franchises.franchise",
            ),
        ),
    ]
