# Generated by Django 6.0.5 on 2026-06-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "franchises",
            "0006_remove_matchplaying11_unique_player_match_playing11_and_more",
        ),
        ("matches", "0004_match_batting_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="batting_first",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batting_first_matches",
                to="franchises.franchise",
            ),
        ),
    ]
