# Generated by Django 6.0.5 on 2026-05-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="city",
        ),
    ]
