# Generated by Django 5.2.1 on 2026-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_team_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
