# Generated by Django 5.2.1 on 2026-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="team_flags/"),
        ),
    ]
