# Generated by Django 6.0.5 on 2026-06-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
