# Generated by Django 6.0.5 on 2026-06-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("franchises", "0003_alter_franchisesquad_franchise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="venue_images/"),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "home_ground",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_venues",
                        to="franchises.franchise",
                    ),
                ),
            ],
        ),
    ]
