# Generated by Django 6.0.5 on 2026-06-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchises", "0002_franchisesquad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franchisesquad",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="squad",
                to="franchises.franchise",
            ),
        ),
    ]
