# Generated by Django 6.0.5 on 2026-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchises", "0005_matchplaying11"),
        ("matches", "0003_match_result"),
        ("players", "0005_alter_ipl_player_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="matchplaying11",
            name="unique_player_match_playing11",
        ),
        migrations.AddConstraint(
            model_name="matchplaying11",
            constraint=models.UniqueConstraint(
                fields=("match", "player"), name="unique_player_match_playing11"
            ),
        ),
    ]
