# Generated by Django 5.2.1 on 2026-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(
                choices=[
                    ("BATTER", "Batter"),
                    ("BOWLER", "Bowler"),
                    ("ALL_ROUNDER", "All-Rounder"),
                    ("WK_BATTER", "Batter/Wicket Keeper"),
                ],
                max_length=50,
            ),
        ),
    ]
