# Generated by Django 6.0.5 on 2026-06-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="batting_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RIGHT_HANDED", "Right-handed"),
                    ("LEFT_HANDED", "Left-handed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="player",
            name="bowling_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RIGHT_ARM_FAST", "Right-arm Fast"),
                    ("LEFT_ARM_FAST", "Left-arm Fast"),
                    ("RIGHT_ARM_MEDIUM", "Right-arm Medium"),
                    ("LEFT_ARM_MEDIUM", "Left-arm Medium"),
                    ("RIGHT_ARM_OFF_BREAK", "Right-arm Off Break"),
                    ("LEFT_ARM_OFF_BREAK", "Left-arm Off Break"),
                    ("RIGHT_ARM_LEG_BREAK", "Right-arm Leg Break"),
                    ("LEFT_ARM_LEG_BREAK", "Left-arm Leg Break"),
                    ("SPIN", "Spin"),
                    ("OFF_SPIN", "Off Spin"),
                    ("LEG_SPIN", "Leg Spin"),
                    ("LEFT_ARM_SPIN", "Left-arm Spin"),
                    ("RIGHT_ARM_SPIN", "Right-arm Spin"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="player_images/"),
        ),
        migrations.AddField(
            model_name="player",
            name="jersey_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
