# Generated by Django 6.0.5 on 2026-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "players",
            "0003_player_batting_style_player_bio_player_bowling_style_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ipl_player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BAT", "Batter"),
                            ("BOWL", "Bowler"),
                            ("AR", "All Rounder"),
                            ("WK", "Wicket Keeper"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "batting_style",
                    models.CharField(
                        blank=True,
                        choices=[("RH", "Right-handed"), ("LH", "Left-handed")],
                        max_length=50,
                    ),
                ),
                (
                    "bowling_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RF", "Right-arm Fast"),
                            ("LF", "Left-arm Fast"),
                            ("RM", "Right-arm Medium"),
                            ("LM", "Left-arm Medium"),
                            ("RO", "Right-arm Off Break"),
                            ("LO", "Left-arm Off Break"),
                            ("RL", "Right-arm Leg Break"),
                            ("LL", "Left-arm Leg Break"),
                            ("SPIN", "Spin"),
                            ("OFF_SPIN", "Off Spin"),
                            ("LEG_SPIN", "Leg Spin"),
                            ("LEFT_ARM_SPIN", "Left-arm Spin"),
                            ("RIGHT_ARM_SPIN", "Right-arm Spin"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_images/"
                    ),
                ),
            ],
        ),
    ]
