# Generated by Django 6.0.5 on 2026-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_ipl_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipl_player",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ipl_player_images/"
            ),
        ),
    ]
